Fix issues reported by `golangci-lint`
```
$ golangci-lint run
generate_perror/main.go:148:11: Error return value of `cmd.Wait` is not checked (errcheck)
		cmd.Wait()
		        ^
src/main.go:294:13: Error return value of `t.mdb.Exec` is not checked (errcheck)
		t.mdb.Exec(fmt.Sprintf("drop database `%s`", strings.ReplaceAll(t.name, "/", "__")))
		          ^
src/main.go:921:18: Error return value of `t.curr.conn.Raw` is not checked (errcheck)
		t.curr.conn.Raw(func(driverConn any) error {
		               ^
generate_perror/main.go:173:9: S1005: unnecessary assignment to the blank identifier (gosimple)
	for i, _ := range codes {
	       ^
generate_perror/main.go:81:6: S1009: should omit nil check; len() for []string is defined as zero (gosimple)
		if m != nil && len(m) == 3 && m[1] != "" && m[2] != "" {
		   ^
generate_perror/main.go:137:7: S1009: should omit nil check; len() for []string is defined as zero (gosimple)
			if m != nil && len(m) == 3 && m[1] != "" && m[2] != "" {
```